/* Cougar-Man: Pac-Man on the BYU campus walkway network.
   Grid + map come from data.js (generated by build.py from the campus SVG). */
(() => {
  const D = window.BYU_DATA;
  const W = D.w, H = D.h, CELL = D.cell;
  const open = (x, y) => x >= 0 && y >= 0 && x < W && y < H && D.grid[y][x] === '.';
  const DIRS = [{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}];
  const key = (x, y) => y * W + x;

  // ---------- layout ----------
  const stage = document.getElementById('stage');
  const canvas = document.getElementById('game');
  const ctx = canvas.getContext('2d');
  const mapImg = document.getElementById('map');
  const mapW = D.x1 - D.x0, mapH = D.y1 - D.y0;
  let S = 1, s = 1;           // canvas px / css px per map unit
  let viewW = mapW, viewH = mapH; // visible map units
  let mobile = false;
  const cam = { x: 0, y: 0 };  // top-left of the view in map units
  function layout() {
    const header = document.querySelector('header'), footer = document.querySelector('footer');
    mobile = Math.min(window.innerWidth, window.innerHeight) < 700 || matchMedia('(pointer: coarse)').matches;
    document.body.classList.toggle('mobile', mobile);
    const vh = (window.visualViewport && window.visualViewport.height) || window.innerHeight;
    let stageW, stageH;
    if (mobile) {
      // near-fullscreen camera view that follows the player
      stageW = window.innerWidth; stageH = vh - header.offsetHeight;
      // zoom in enough to read the maze (~22 cells across) but never so far out that the map doesn't fill the screen
      s = Math.max(stageW / mapW, stageH / mapH, Math.min(stageW, stageH) / (CELL * 22));
    } else {
      const availW = Math.min(window.innerWidth - 16, 1100);
      const availH = vh - header.offsetHeight - footer.offsetHeight - 16;
      s = Math.max(0.3, Math.min(availW / mapW, availH / mapH));
      stageW = mapW * s; stageH = mapH * s;
    }
    viewW = stageW / s; viewH = stageH / s;
    stage.style.setProperty('--w', stageW + 'px');
    stage.style.setProperty('--h', stageH + 'px');
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(stageW * dpr);
    canvas.height = Math.round(stageH * dpr);
    S = s * dpr;
    mapImg.style.width = (mapW * s) + 'px'; mapImg.style.height = (mapH * s) + 'px';
    cam.x = cam.y = NaN; // snap camera on next draw
  }
  window.addEventListener('resize', layout);
  if (window.visualViewport) window.visualViewport.addEventListener('resize', layout);
  layout();
  function updateCamera(dt) {
    const tx = player ? player.x : mapW / 2, ty = player ? player.y : mapH / 2;
    const clamp = (v, span, total) => span >= total ? (total - span) / 2 : Math.max(0, Math.min(total - span, v));
    const gx = clamp(tx - viewW / 2, viewW, mapW), gy = clamp(ty - viewH / 2, viewH, mapH);
    if (isNaN(cam.x)) { cam.x = gx; cam.y = gy; }
    else { const k = Math.min(1, dt * 7); cam.x += (gx - cam.x) * k; cam.y += (gy - cam.y) * k; }
    mapImg.style.transform = `translate(${-cam.x * s}px, ${-cam.y * s}px)`;
  }

  // cell (grid) -> map units (center of cell)
  const cx = gx => gx * CELL + CELL / 2;
  const cy = gy => gy * CELL + CELL / 2;

  // ---------- special cells ----------
  const openCells = [];
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (open(x, y)) openCells.push({x, y});
  const degree = c => DIRS.filter(d => open(c.x + d.x, c.y + d.y)).length;
  function nearestOpen(mx, my, minDegree = 0) { // map coords (absolute) -> nearest open cell
    const lx = mx - D.x0, ly = my - D.y0;
    let best = null, bd = Infinity;
    for (const c of openCells) {
      if (degree(c) < minDegree) continue;
      const d = (cx(c.x) - lx) ** 2 + (cy(c.y) - ly) ** 2;
      if (d < bd) { bd = d; best = c; }
    }
    return best;
  }
  const bld = code => D.buildings.find(b => b.code === code);
  const hgb = bld('HGB');
  const SPAWN = hgb ? nearestOpen(hgb.x, hgb.y) : nearestOpen(D.x0 + 80, D.y1 - 80);
  const START = nearestOpen(800, 880, 3); // a junction in Brigham Square, so the first swipe usually works
  const corners = [
    nearestOpen(D.x0, D.y0), nearestOpen(D.x1, D.y0),
    nearestOpen(D.x0, D.y1), nearestOpen(D.x1, D.y1),
  ];
  const POWER = new Set(corners.map(c => key(c.x, c.y)));

  // BFS distance field from a cell
  function bfs(sx, sy) {
    const dist = new Int32Array(W * H).fill(-1);
    const q = [key(sx, sy)]; dist[q[0]] = 0;
    for (let i = 0; i < q.length; i++) {
      const k = q[i], x = k % W, y = (k - x) / W;
      for (const d of DIRS) {
        const nx = x + d.x, ny = y + d.y;
        if (open(nx, ny) && dist[key(nx, ny)] < 0) { dist[key(nx, ny)] = dist[k] + 1; q.push(key(nx, ny)); }
      }
    }
    return dist;
  }
  const distToSpawn = bfs(SPAWN.x, SPAWN.y);

  // ---------- state ----------
  const GHOST_DEFS = [
    { name: 'Proctor',             color: '#ff3b30', scatter: corners[1], delay: 0 },
    { name: 'Parking Enforcement', color: '#ff7fd1', scatter: corners[0], delay: 3 },
    { name: 'Group Project',       color: '#3fd8ff', scatter: corners[3], delay: 6 },
    { name: 'Finals Week',         color: '#ffa03b', scatter: corners[2], delay: 9 },
  ];
  let dots, dotsLeft, score = 0, high = +(localStorage.getItem('cougarman-high') || 0), lives = 3, level = 1;
  let player, ghosts, mode, modeTimer, frightTimer, ghostCombo, state = 'idle', stateTimer = 0;
  let audioOn = true;

  function makeEntity(cell, speed) {
    return { from: {...cell}, to: {...cell}, t: 1, dir: null, want: null, speed, x: cx(cell.x), y: cy(cell.y) };
  }
  function resetPositions() {
    player = makeEntity(START, 6.2 + level * 0.25);
    player.mouth = 0;
    ghosts = GHOST_DEFS.map((g, i) => ({
      ...makeEntity(SPAWN, 5.4 + level * 0.3), def: g, id: i,
      state: 'waiting', wait: g.delay, fright: false,
    }));
    mode = 'scatter'; modeTimer = 7; frightTimer = 0; ghostCombo = 0;
  }
  function newLevel() {
    dots = new Set(openCells.map(c => key(c.x, c.y)));
    dots.delete(key(START.x, START.y));
    dotsLeft = dots.size;
    resetPositions();
  }
  let nextLife = 10000;
  function newGame() {
    score = 0; lives = 3; level = 1; nextLife = 10000;
    newLevel();
    setState('ready', 2.2);
    sfx('start');
    updateHud();
  }
  function setState(s, t) { state = s; stateTimer = t || 0; }

  // ---------- movement ----------
  function pos(e) {
    e.x = cx(e.from.x) + (cx(e.to.x) - cx(e.from.x)) * e.t;
    e.y = cy(e.from.y) + (cy(e.to.y) - cy(e.from.y)) * e.t;
  }
  function reverse(e) {
    if (e.t >= 1 || !e.dir) return;
    [e.from, e.to] = [e.to, e.from]; e.t = 1 - e.t; e.dir = {x: -e.dir.x, y: -e.dir.y};
  }
  // advance entity along the grid; `choose(cell)` returns next dir or null when it arrives at a cell center
  function advance(e, dt, choose) {
    let budget = e.speed * dt;
    while (budget > 0) {
      if (e.t >= 1) {
        e.from = {...e.to};
        const d = choose(e.from);
        if (!d) { e.dir = null; return; }
        e.dir = d; e.to = {x: e.from.x + d.x, y: e.from.y + d.y}; e.t = 0;
      }
      const step = Math.min(budget, 1 - e.t);
      e.t += step; budget -= step;
    }
    pos(e);
  }
  const playerChoose = c => {
    if (player.want && open(c.x + player.want.x, c.y + player.want.y)) { const d = player.want; player.want = null; return d; }
    if (player.dir && open(c.x + player.dir.x, c.y + player.dir.y)) return player.dir;
    return null;
  };
  function setWant(d) {
    player.want = d;
    // reversing mid-edge is allowed immediately
    if (player.dir && d.x === -player.dir.x && d.y === -player.dir.y && player.t < 1) { reverse(player); player.want = null; }
    else if (player.t >= 1 && open(player.to.x + d.x, player.to.y + d.y)) { player.want = d; }
  }

  function ghostChoose(g, c) {
    const options = DIRS.filter(d => open(c.x + d.x, c.y + d.y));
    if (!options.length) return null;
    const back = g.dir ? {x: -g.dir.x, y: -g.dir.y} : null;
    let cand = options.filter(d => !back || d.x !== back.x || d.y !== back.y);
    if (!cand.length) cand = options; // dead end: allowed to turn around

    if (g.state === 'eaten') {
      return cand.reduce((a, b) => distToSpawn[key(c.x + b.x, c.y + b.y)] < distToSpawn[key(c.x + a.x, c.y + a.y)] ? b : a);
    }
    if (g.fright) return cand[Math.floor(Math.random() * cand.length)];

    let target;
    const pc = player.to;
    if (mode === 'scatter') target = g.def.scatter;
    else switch (g.id) {
      case 0: // true shortest path to the player
        return cand.reduce((a, b) => playerDist[key(c.x + b.x, c.y + b.y)] < playerDist[key(c.x + a.x, c.y + a.y)] ? b : a);
      case 1: { const d = player.dir || {x:0,y:-1}; target = {x: pc.x + 4 * d.x, y: pc.y + 4 * d.y}; break; }
      case 2: { const d = player.dir || {x:0,y:-1}; const ax = pc.x + 2 * d.x, ay = pc.y + 2 * d.y;
                const b = ghosts[0].to; target = {x: 2 * ax - b.x, y: 2 * ay - b.y}; break; }
      case 3: { const far = (c.x - pc.x) ** 2 + (c.y - pc.y) ** 2 > 64;
                if (far) return cand.reduce((a, b) => playerDist[key(c.x + b.x, c.y + b.y)] < playerDist[key(c.x + a.x, c.y + a.y)] ? b : a);
                target = g.def.scatter; break; }
    }
    return cand.reduce((a, b) => {
      const da = (c.x + a.x - target.x) ** 2 + (c.y + a.y - target.y) ** 2;
      const db = (c.x + b.x - target.x) ** 2 + (c.y + b.y - target.y) ** 2;
      return db < da ? b : a;
    });
  }
  let playerDist = null;

  // ---------- update ----------
  function update(dt) {
    if (state === 'ready' || state === 'dying' || state === 'levelclear' || state === 'over') {
      stateTimer -= dt;
      if (stateTimer <= 0) {
        if (state === 'ready') setState('play');
        else if (state === 'dying') { if (lives > 0) { resetPositions(); setState('ready', 1.5); } else setState('over'); overlay(true, 'GAME OVER', `Final score ${score}. The Testing Center closes at 10.`); }
        else if (state === 'levelclear') { level++; newLevel(); setState('ready', 2); updateHud(); }
      }
      if (state !== 'play') { updateSiren(); return; }
    }
    if (state !== 'play') { updateSiren(); return; }
    updateSiren();

    // mode timers
    if (frightTimer > 0) {
      frightTimer -= dt;
      if (frightTimer <= 0) ghosts.forEach(g => { g.fright = false; if (g.state === 'active') g.speed = 5.4 + level * 0.3; });
    } else {
      modeTimer -= dt;
      if (modeTimer <= 0) {
        mode = mode === 'scatter' ? 'chase' : 'scatter';
        modeTimer = mode === 'scatter' ? Math.max(3, 7 - level) : 20;
        ghosts.forEach(g => g.state === 'active' && reverse(g));
      }
    }

    // player
    advance(player, dt, playerChoose);
    player.mouth += dt * 10;
    const pk = key(player.to.x, player.to.y);
    if (player.t > 0.5 && dots.has(pk)) {
      dots.delete(pk); dotsLeft--;
      if (POWER.has(pk)) {
        score += 50; frightTimer = Math.max(3, 8 - level * 0.5); ghostCombo = 0;
        ghosts.forEach(g => { if (g.state === 'active') { g.fright = true; g.speed = 3.4; reverse(g); } });
        sfx('power');
      } else { score += 10; sfx('waka'); }
      if (score >= nextLife) { nextLife += 10000; lives++; sfx('life'); }
      updateHud();
      if (dotsLeft === 0) { setState('levelclear', 2); sfx('level'); return; }
    }

    // ghosts
    playerDist = bfs(player.to.x, player.to.y);
    for (const g of ghosts) {
      if (g.state === 'waiting') { g.wait -= dt; if (g.wait <= 0) g.state = 'active'; else continue; }
      advance(g, dt, c => ghostChoose(g, c));
      if (g.state === 'eaten' && g.t >= 1 && g.to.x === SPAWN.x && g.to.y === SPAWN.y) {
        g.state = 'active'; g.fright = false; g.speed = 5.4 + level * 0.3;
      }
      // collision
      const dx = g.x - player.x, dy = g.y - player.y;
      if (dx * dx + dy * dy < (CELL * 0.7) ** 2) {
        if (g.state === 'eaten') continue;
        if (g.fright) {
          g.state = 'eaten'; g.fright = false; g.speed = 11;
          score += 200 * (2 ** ghostCombo); ghostCombo++; updateHud(); sfx('ghost');
        } else {
          lives--; updateHud(); sfx('die'); setState('dying', 1.6);
          return;
        }
      }
    }
    updateNear();
  }

  // ---------- drawing ----------
  let lastDraw = 0;
  function draw(now) {
    updateCamera(Math.min(0.1, (now - lastDraw) / 1000)); lastDraw = now;
    ctx.setTransform(S, 0, 0, S, -cam.x * S, -cam.y * S);
    ctx.clearRect(cam.x, cam.y, viewW, viewH);

    // corridors
    ctx.lineCap = 'round'; ctx.lineJoin = 'round';
    ctx.strokeStyle = 'rgba(0,46,93,0.28)'; ctx.lineWidth = CELL * 0.55;
    ctx.beginPath();
    for (const c of openCells) {
      if (open(c.x + 1, c.y)) { ctx.moveTo(cx(c.x), cy(c.y)); ctx.lineTo(cx(c.x + 1), cy(c.y)); }
      if (open(c.x, c.y + 1)) { ctx.moveTo(cx(c.x), cy(c.y)); ctx.lineTo(cx(c.x), cy(c.y + 1)); }
    }
    ctx.stroke();

    // dots
    const pulse = 0.85 + 0.25 * Math.sin(now / 150);
    for (const k of dots) {
      const x = k % W, y = (k - x) / W;
      if (POWER.has(k)) {
        ctx.fillStyle = '#ffffff'; ctx.beginPath(); ctx.arc(cx(x), cy(y), CELL * 0.36 * pulse, 0, 7); ctx.fill();
        ctx.fillStyle = '#f5c842'; ctx.beginPath(); ctx.arc(cx(x), cy(y), CELL * 0.26 * pulse, 0, 7); ctx.fill();
      } else {
        ctx.fillStyle = '#f5c842'; ctx.beginPath(); ctx.arc(cx(x), cy(y), CELL * 0.13, 0, 7); ctx.fill();
      }
    }

    if (!player) return;
    // ghosts
    for (const g of ghosts) {
      if (g.state === 'waiting' && g.wait > 0 && g.def.delay > 0 && state === 'ready') continue;
      drawGhost(g, now);
    }
    // player
    const r = CELL * 0.48;
    let mouth = state === 'play' && player.dir ? Math.abs(Math.sin(player.mouth)) * 0.9 : 0.3;
    if (state === 'dying') { mouth = Math.min(Math.PI, (1.6 - stateTimer) * 2.2); }
    const ang = player.dir ? Math.atan2(player.dir.y, player.dir.x) : 0;
    ctx.fillStyle = '#ffd400'; ctx.strokeStyle = '#7a5b00'; ctx.lineWidth = 0.8;
    ctx.beginPath();
    ctx.moveTo(player.x, player.y);
    ctx.arc(player.x, player.y, r, ang + mouth, ang + Math.PI * 2 - mouth);
    ctx.closePath(); ctx.fill(); ctx.stroke();
    // eye
    if (state !== 'dying') {
      const ex = player.x + Math.cos(ang - Math.PI / 2) * r * 0.5 + Math.cos(ang) * r * 0.1;
      const ey = player.y + Math.sin(ang - Math.PI / 2) * r * 0.5 + Math.sin(ang) * r * 0.1;
      ctx.fillStyle = '#062'; ctx.beginPath(); ctx.arc(ex, ey, r * 0.16, 0, 7); ctx.fill();
    }

    // ready text
    if (state === 'ready') {
      ctx.font = `900 ${CELL * 1.8}px sans-serif`; ctx.textAlign = 'center';
      ctx.fillStyle = '#f5c842'; ctx.strokeStyle = '#061a36'; ctx.lineWidth = 3;
      ctx.strokeText('READY!', player.x, player.y - CELL * 1.6); ctx.fillText('READY!', player.x, player.y - CELL * 1.6);
    }
  }
  function drawGhost(g, now) {
    const r = CELL * 0.48, x = g.x, y = g.y;
    const eyes = g.state === 'eaten';
    if (!eyes) {
      let col = g.def.color;
      if (g.fright) col = (frightTimer < 2 && Math.floor(now / 200) % 2) ? '#ffffff' : '#2438ff';
      ctx.fillStyle = col;
      ctx.beginPath();
      ctx.arc(x, y - r * 0.15, r, Math.PI, 0);
      const wob = Math.floor(now / 120) % 2 ? 0 : r * 0.25;
      ctx.lineTo(x + r, y + r * 0.85);
      for (let i = 0; i < 3; i++) {
        const bx = x + r - (i * 2 + 1) * r / 3;
        ctx.lineTo(bx, y + r * 0.85 - (i % 2 === 0 ? r * 0.3 : 0) + (i === 1 ? wob : 0));
      }
      ctx.lineTo(x - r, y + r * 0.85);
      ctx.closePath(); ctx.fill();
    }
    if (g.fright && !eyes) {
      ctx.fillStyle = '#ffd6d6';
      ctx.fillRect(x - r * 0.45, y - r * 0.3, r * 0.22, r * 0.22);
      ctx.fillRect(x + r * 0.23, y - r * 0.3, r * 0.22, r * 0.22);
      ctx.strokeStyle = '#ffd6d6'; ctx.lineWidth = 0.8; ctx.beginPath();
      for (let i = 0; i < 4; i++) { ctx.lineTo(x - r * 0.5 + i * r * 0.33, y + r * 0.25 + (i % 2 ? r * 0.15 : 0)); }
      ctx.stroke();
      return;
    }
    const d = g.dir || {x: 0, y: 0};
    for (const s of [-1, 1]) {
      ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.ellipse(x + s * r * 0.36, y - r * 0.2, r * 0.22, r * 0.28, 0, 0, 7); ctx.fill();
      ctx.fillStyle = '#1a2a6c'; ctx.beginPath(); ctx.arc(x + s * r * 0.36 + d.x * r * 0.12, y - r * 0.2 + d.y * r * 0.14, r * 0.12, 0, 7); ctx.fill();
    }
  }

  // ---------- HUD / overlay ----------
  const $ = id => document.getElementById(id);
  function updateHud() {
    $('score').textContent = score;
    if (score > high) { high = score; localStorage.setItem('cougarman-high', high); }
    $('high').textContent = high;
    $('level').textContent = level;
    $('lives').textContent = '●'.repeat(Math.max(0, lives));
  }
  function overlay(show, title, text) {
    const o = $('overlay');
    o.classList.toggle('hidden', !show);
    if (title) o.querySelector('h2').textContent = title;
    if (text) o.querySelector('p').textContent = text;
    if (show) $('start').textContent = state === 'over' ? 'Play again' : (state === 'paused' ? 'Resume' : 'Play');
    if (show) sirenSet('off');
  }
  let nearCode = '';
  function updateNear() {
    const px = player.x + D.x0, py = player.y + D.y0;
    let best = null, bd = 55 * 55;
    for (const b of D.buildings) { if (!b.code) continue; const d = (b.x - px) ** 2 + (b.y - py) ** 2; if (d < bd) { bd = d; best = b; } }
    const code = best ? best.code : '';
    if (code !== nearCode) { nearCode = code; $('near').textContent = best ? `${best.code} — ${best.name}` : ' '; }
  }

  // ---------- input ----------
  const KEYS = { ArrowUp: {x:0,y:-1}, ArrowDown: {x:0,y:1}, ArrowLeft: {x:-1,y:0}, ArrowRight: {x:1,y:0},
                 w: {x:0,y:-1}, s: {x:0,y:1}, a: {x:-1,y:0}, d: {x:1,y:0} };
  window.addEventListener('keydown', e => {
    const k = e.key.length === 1 ? e.key.toLowerCase() : e.key;
    if (KEYS[k]) { e.preventDefault(); if (state === 'play') setWant(KEYS[k]); else if (state === 'idle') start(); }
    if (k === 'p' || k === 'Escape') togglePause();
    if (k === 'm') setAudio(!audioOn);
    if (k === 'Enter' || k === ' ') { if (state === 'idle' || state === 'over' || state === 'paused') start(); }
  });
  // swipe anywhere: the turn fires as soon as the finger has moved far enough (no need to lift)
  let touch = null;
  window.addEventListener('pointerdown', e => { if (e.target.closest('button')) return; touch = {x: e.clientX, y: e.clientY}; initAudio(); }, {passive: true});
  window.addEventListener('pointermove', e => {
    if (!touch) return;
    const dx = e.clientX - touch.x, dy = e.clientY - touch.y;
    if (Math.abs(dx) < 22 && Math.abs(dy) < 22) return;
    touch = null;
    if (state === 'play') setWant(Math.abs(dx) > Math.abs(dy) ? {x: Math.sign(dx), y: 0} : {x: 0, y: Math.sign(dy)});
  }, {passive: true});
  window.addEventListener('pointerup', () => { touch = null; });
  $('start').addEventListener('click', start);
  $('mute').addEventListener('click', () => setAudio(!audioOn));
  function setAudio(on) {
    audioOn = on; $('mute').textContent = on ? '🔊' : '🔇';
    try { localStorage.setItem('cougarman-audio', on ? '1' : '0'); } catch (e) {}
    if (!on) sirenSet('off');
  }
  function start() {
    initAudio();
    if (state === 'paused') { setState('play'); overlay(false); return; }
    newGame(); overlay(false);
    // go fullscreen on phones when supported (iOS Safari ignores this; the layout is near-fullscreen anyway)
    if (mobile && document.documentElement.requestFullscreen && !document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
    }
  }
  function togglePause() {
    if (state === 'play') { setState('paused'); overlay(true, 'PAUSED', 'Press P or Resume to keep going.'); }
    else if (state === 'paused') { setState('play'); overlay(false); }
  }
  document.addEventListener('visibilitychange', () => { if (document.hidden && state === 'play') togglePause(); });

  // ---------- tiny synth sfx ----------
  let AC = null;
  function initAudio() { if (!AC) { try { AC = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) {} } if (AC && AC.state === 'suspended') AC.resume(); }
  let lastWaka = 0;
  function sfx(kind) {
    if (!AC || !audioOn) return;
    const t = AC.currentTime;
    const tone = (f0, f1, dur, type = 'square', vol = 0.05, at = 0) => {
      const o = AC.createOscillator(), g = AC.createGain();
      o.type = type; o.frequency.setValueAtTime(f0, t + at); o.frequency.exponentialRampToValueAtTime(f1, t + at + dur);
      g.gain.setValueAtTime(vol, t + at); g.gain.exponentialRampToValueAtTime(0.0001, t + at + dur);
      o.connect(g).connect(AC.destination); o.start(t + at); o.stop(t + at + dur + 0.02);
    };
    switch (kind) {
      case 'waka': if (t - lastWaka < 0.09) return; lastWaka = t; wakaHi = !wakaHi;
        wakaHi ? tone(180, 420, 0.08, 'square', 0.04) : tone(420, 180, 0.08, 'square', 0.04); break;
      case 'power': tone(200, 800, 0.35, 'sawtooth', 0.05); tone(100, 400, 0.35, 'sawtooth', 0.03); break;
      case 'ghost': tone(300, 1400, 0.3, 'square', 0.06); tone(300, 1400, 0.3, 'square', 0.04, 0.15); break;
      case 'die': for (let i = 0; i < 6; i++) tone(500 - i * 60, 200 - i * 20, 0.18, 'triangle', 0.06, i * 0.18);
        tone(120, 40, 0.5, 'sawtooth', 0.05, 1.1); break;
      case 'level': [523, 659, 784, 1047].forEach((f, i) => tone(f, f, 0.15, 'square', 0.05, i * 0.12)); break;
      case 'start': // opening jingle
        [392, 523, 659, 784, 659, 784, 1047].forEach((f, i) => tone(f, f, 0.14, 'square', 0.05, i * 0.13));
        [196, 262, 330, 392, 330, 392, 523].forEach((f, i) => tone(f, f, 0.14, 'triangle', 0.05, i * 0.13)); break;
      case 'life': [784, 988, 1175, 1568].forEach((f, i) => tone(f, f * 1.5, 0.2, 'square', 0.05, i * 0.1)); break;
    }
  }
  let wakaHi = false;

  // background siren: continuous oscillator whose pitch wobbles; changes character per game phase
  let siren = null, sirenKind = 'off';
  function sirenSet(kind) {
    if (kind === sirenKind) return;
    if (!AC) { sirenKind = kind === 'off' ? 'off' : sirenKind; return; }
    const t = AC.currentTime;
    if (kind === 'off' || !audioOn) {
      if (siren) { siren.g.gain.setTargetAtTime(0, t, 0.05); siren.o.stop(t + 0.4); siren.lfo.stop(t + 0.4); siren = null; }
      sirenKind = 'off'; return;
    }
    if (!siren) {
      const o = AC.createOscillator(), lfo = AC.createOscillator(), depth = AC.createGain(), g = AC.createGain();
      o.type = 'triangle'; lfo.type = 'sine';
      lfo.connect(depth).connect(o.frequency); o.connect(g).connect(AC.destination);
      g.gain.setValueAtTime(0, t); o.start(t); lfo.start(t);
      siren = { o, lfo, depth, g };
    }
    const p = { normal: [200 + level * 15, 3.5, 45, 0.035], fright: [330, 9, 140, 0.04], eyes: [640, 16, 260, 0.035] }[kind];
    siren.o.frequency.setTargetAtTime(p[0], t, 0.05);
    siren.lfo.frequency.setTargetAtTime(p[1], t, 0.05);
    siren.depth.gain.setTargetAtTime(p[2], t, 0.05);
    siren.g.gain.setTargetAtTime(p[3], t, 0.1);
    sirenKind = kind;
  }
  function updateSiren() {
    if (state !== 'play' || !audioOn) return sirenSet('off');
    if (ghosts.some(g => g.state === 'eaten')) return sirenSet('eyes');
    sirenSet(frightTimer > 0 ? 'fright' : 'normal');
  }

  // ---------- loop ----------
  let last = performance.now();
  function frame(now) {
    // fixed-ish timestep: sub-step long frames so slow devices don't slow the game down
    let dt = Math.min(0.25, (now - last) / 1000); last = now;
    while (dt > 0) { const s = Math.min(dt, 1 / 60); update(s); dt -= s; }
    draw(now);
    requestAnimationFrame(frame);
  }
  // debug hook (used for automated testing)
  window.CougarMan = { update, draw, setWant, start, get state() { return state; }, get score() { return score; },
    get player() { return player; }, get ghosts() { return ghosts; }, get dotsLeft() { return dotsLeft; }, get lives() { return lives; } };
  try { setAudio(localStorage.getItem('cougarman-audio') !== '0'); } catch (e) {}
  updateHud();
  // show the empty maze behind the start overlay
  dots = new Set(openCells.map(c => key(c.x, c.y)));
  requestAnimationFrame(frame);
})();
